services:
  mariadb:
    image: mariadb:10.11
    container_name: my_mariadb
    security_opt:
      - seccomp:unconfined
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
      - ./backup:/backup
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_ROOT_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      timeout: 5s
      retries: 10

  backup:
    build: .
    image: greyhard/mysql-cron-backup-pgp
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./backup:/backup
      # Uncomment to use PGP encryption with mounted keys
      - ./secrets:/secrets:ro
    environment:
      - MYSQL_HOST=my_mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=${MARIADB_ROOT_PASSWORD}
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - CRON_TIME=0 3 * * *
      - GZIP_LEVEL=9
      # Uncomment to enable split mode (separate directory per backup)
      # - DATABASE_SPLIT_TO_FILE=true
      # Enable PGP encryption
      - PGP_KEY_FILE=file:/secrets/pgp_public_key
      - PGP_PRIVATE_KEY_FILE=/secrets/pgp_private_key
    restart: unless-stopped

volumes:
  data:
